- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Remove old HTTP content
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent

- name: Create a HTTP document directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: directory
