- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Remove old HTTP content
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent

- name: Create a HTTP document directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: directory

- name: Download frontend App conent
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copy roboshop config file o Nginx
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Start Nginx service
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx
    enabled: true